### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by sureshHARDIYA** [Jam3/ffmpeg-gif#2]
My Command, was: `ffmpeg-gif order_flow.mov order.gif`
The error I get is,  

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by niborb** [comment]
I guess you need to install ffmpeg :)

**Comment by sureshHARDIYA** [comment]
Ah, I should have closed that long ago.
